[package]
name = "auth0-user-gatekeeper"
version = "0.0.1"
edition = "2024"

[dependencies]
axum = "0.8.4"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
validator = { version = "0.16", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
